apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rstudio
  region: us-east-2
  version: "1.21"

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
      - namespace: rstudio
  - name: flux-system
    selectors:
      - namespace: flux-system
  - name: appmesh-system
    selectors:
      - namespace: appmesh-system
  - name: aws-system
    selectors:
      - namespace: aws-system
  - name: cert-manager
    selectors:
      - namespace: cert-manager

iam:
  # serviceRoleARN: arn:aws:iam::534014647921:role/EKSClusterRole
  # fargatePodExecutionRoleARN: arn:aws:iam::534014647921:role/EKSFargatePodRole
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      attachPolicyARNs: 
        - arn:aws:iam::365268860483:policy/AmazonEKS_EFS_CSI_Driver_Policy
    - metadata:
        name: appmesh-controller
        namespace: appmesh-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AWSCloudMapFullAccess
        - arn:aws:iam::aws:policy/AWSAppMeshFullAccess
    - metadata:
        name: aws-lb-controller
        namespace: aws-system
      attachPolicyARNs:
        -  arn:aws:iam::365268860483:policy/AWSLoadBalancerControllerIAMPolicy
    - metadata:
        name: cert-manager
        namespace: cert-maanger
      attachPolicyARNs:
        - 

addOns:
  - name: vpc-cni
  - name: kube-proxy
  - name: core-dns
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      autoScaler: true
      externalDNS: true
      awsLoadBalancerController: true
      certManager: true
      ebsCSIController: true
      efsCSICOntroller: true

  # nat:
  #   gateway: Disable
    # clusterEndpoints:
    #   privateAccess: true
    #   publicAccess: false

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

gitops:
  flux:
    gitProvider: github
    flags:
      owner: "walkermiller"
      repository: "rstudio-eks"
      private: "false"
      branch: main
      namespace: flux-system
      path: clusters/rstudio