apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-lb-controller
  namespace: aws-system
spec:
  interval: 1m
  releaseName: aws-lb-controller
  chart:
    spec:
      chart:  aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: ekscharts
        namespace: flux-system
      interval: 1m
  values:
    serviceAccount:
      create: false
      name: aws-lb-controller
    region: us-east-2
    vpcId: vpc-0c9e812ecc563d09c
    clusterName: rstudio
    image:
      respoitory: 602401143452.dkr.ecr.us-east-2.amazonaws.com/amazon/aws-load-balancer-controller
